version: "2.1"

services:
  engage:
    image: dadarek/wait-for-dependencies
    depends_on:
      - database
      - redis
      - php
      - phpunit
      - nginx
      - cache
    command: database:3306 redis:6379 php:9000 socketio:3030 nginx:80 cache:11211
  nginx:
    image: prooph/nginx:www
    ports:
      - "8087:80"
      - "444:443"
      - "3031:3030"
    links:
      - php:php
      - socketio:socketio

    depends_on:
      - database
      - redis
      - php
      - socketio
      - data
    volumes:
      - f:/_Containers/multiple-sites/machine/nginx/sites-enabled:/etc/nginx/sites-enabled
      - f:/_Containers/multiple-sites/machine/nginx/log:/var/log/nginx
    volumes_from:
      - data
      - socketio

  php:
    env_file: "${PHP_ENV_FILE}"
    image: "alterway/php:${PHP_VERSION}-fpm"
    depends_on:
     - database
     - redis
    links:
     - database:database
    volumes_from:
     - data

  socketio:
    image: node:7
    ports:
     - "3001:3000"
    depends_on:
     - redis
    links:
     - redis:redis
    volumes:
     - "f:/_Containers/multiple-sites/machine/socketio:/src"
    command: bash -c "chmod -R 777 /src && cd /src && rm -rf node_modules && npm install nodemon -g && npm install && nodemon -L server"


  phpunit:
    image: binarydata/phpunit
    depends_on:
     - database
     - redis
    links:
     - database:database
     - redis:redis
    volumes_from:
     - data

  data:
    image: alpine:latest
    volumes:
      - "${SITES_FOLDER}:/var/www"
      - "${SSH_FOLDER}:/root/.ssh"
    command: /bin/sh -c "/bin/true && chmod -R 777 /var/www"

  database:
    image: "mysql:${MYSQL_VERSION}"
    env_file: "${MYSQL_ENV_FILE}"
    #environment:
    #    MYSQL_ROOT_PASSWORD: ${AJ_MYSQL_ROOT_PASSWORD}
    #    MYSQL_DATABASE: ${AJ_MYSQL_DATABASE}
    #    MYSQL_USER: ${AJ_MYSQL_USER}
    #    MYSQL_PASSWORD: ${AJ_MYSQL_PASSWORD}
    #    MYSQL_ALLOW_EMPTY_PASSWORD: ${AJ_MYSQL_ALLOW_EMPTY_PASSWORD}
    ports:
      - "33062:3306"
    volumes:
      - f:/_Containers/multiple-sites/machine/mysql/databases:/var/lib/mysql
      - f:/_Containers/multiple-sites/machine/mysql/cnf:/etc/mysql/conf.d
      - f:/_Containers/multiple-sites/machine/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  cache:
    image: memcached
    ports:
      - "11212:11211"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"